### ISSUE TITLE
How to use http-add-on and keda for autoscaling across multiple namespaces

### ISSUE THREAD

**Issue by ishallbethat** [kedacore/http-add-on#629] opened 2023-03-12 07:45 UTC
My deployment and service in namespace A
My keda and http-add-on is in Keda namespace . So the interceptor is in Keda namespace.
My Nginx ingress is in namespace C

How can I make sure the nginx ingress routes the request to interceptor proxy then to service correctly ?

**Comment by ishallbethat** [comment] 2023-03-12 07:53
And also Keda and http add on must be in the same namespace ?

**Comment by tomkerkhove** [comment] 2023-03-13 09:10
Hi, this is a duplicate of https://github.com/kedacore/http-add-on/discussions/566

**Closed by tomkerkhove** 2023-03-13 09:10 UTC
